### ISSUE TITLE
Transfer Capture Error in Outfile

### ISSUE THREAD

**Issue by AlicePrael** [ucancallmealicia/born-digital-accessioner#3]
Transfer Capture event records are created in ArchivesSpace, but there is no event record URL in the outfile.  This does not appear to affect any other event type, only transfer_capture.  
The tool does not report an error and there aren't any error messages in the log file.

**Comment by ucancallmealicia** [comment]
It looks like what is actually happening is that the first event URI is not being written to the outfile - e.g. if 3 events are created only the 2nd + 3rd event URIs are written to the file. Was able to get a transfer_capture URI to write to the outfile so doesn't seem related to the type, but rather the position on the spreadsheet.

**Comment by ucancallmealicia** [comment]
`row.append(new_event['uri'])` missing from first call to event creation function (lines 458-459). Fix in next commit
